- name: demo on play level variables
  hosts: localhost
  connection: local # it will not ask for username and password
  
  tasks:
  - debug:
      msg: "Hi, I am learning {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}"